apiVersion: batch/v1
kind: Job
metadata:
  name: memory-game-job
spec:
  template:
    spec:
      containers:
      - name: memory-game-job
        image: yash5090/memory-game:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
