apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-game-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: memory-game
  template:
    metadata:
      labels:
        app: memory-game
    spec:
      containers:
        - name: memory-game
          image: yash5090/memory-game:latest # Replace with the actual image tag
          ports:
            - containerPort: 5000 # Replace with the port your Tetris game listens on
